import { MULTIPLE_CHOICE_OPTION_COUNT, type QuestionDraft } from "@/domain/question";
import type { GeneratedQuestion } from "@/server/ai/schemas";

const MAX_RUBRIC_POINTS = 6;
const MAX_CODE_LANGUAGE_LENGTH = 30;

/**
 * Converts a question generated by Claude into a validated draft, or returns
 * null if it is malformed (wrong concept, bad option set, missing answer key).
 * Rejecting bad questions is cheaper than showing a learner a broken one.
 */
export function toQuestionDraft(
  generated: GeneratedQuestion,
  allowedConceptIds: ReadonlySet<string>,
): QuestionDraft | null {
  const prompt = generated.prompt.trim();
  const explanation = generated.explanation.trim();
  const code = nonEmpty(generated.code);
  const codeLanguage = code ? normalizeLanguage(generated.codeLanguage) : null;

  if (!allowedConceptIds.has(generated.conceptId) || !prompt || !explanation) return null;
  const base = { conceptId: generated.conceptId, prompt, explanation, code, codeLanguage };

  switch (generated.type) {
    case "multiple_choice": {
      const options = generated.options.map((option) => option.trim());
      const index = generated.correctOptionIndex;
      const distinct = new Set(options.map((option) => option.toLowerCase()));
      const isValid =
        options.length === MULTIPLE_CHOICE_OPTION_COUNT &&
        options.every(Boolean) &&
        distinct.size === options.length &&
        index !== null &&
        Number.isInteger(index) &&
        index >= 0 &&
        index < options.length;
      return isValid
        ? { ...base, type: "multiple_choice", options, correctOptionIndex: index }
        : null;
    }
    case "short_answer": {
      const expectedAnswer = nonEmpty(generated.expectedAnswer);
      const rubric = generated.rubric.map((point) => point.trim()).filter(Boolean);
      const isValid = expectedAnswer && rubric.length > 0 && rubric.length <= MAX_RUBRIC_POINTS;
      return isValid ? { ...base, type: "short_answer", expectedAnswer, rubric } : null;
    }
    case "code_output": {
      const expectedAnswer = nonEmpty(generated.expectedAnswer);
      return code && expectedAnswer ? { ...base, type: "code_output", code, expectedAnswer } : null;
    }
  }
}

function nonEmpty(value: string | null): string | null {
  const trimmed = value?.trim();
  return trimmed ? trimmed : null;
}

/** Keeps language labels short and plain, e.g. "TypeScript" -> "typescript". */
function normalizeLanguage(language: string | null): string {
  const normalized = (language ?? "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9#+.-]/g, "")
    .slice(0, MAX_CODE_LANGUAGE_LENGTH);
  return normalized || "text";
}
